### ISSUE TITLE
NLA

### ISSUE THREAD

**Issue by AnneleenArtois** [microsoft/MCW-Migrate-EDW-to-Azure-SQL-Data-Warehouse#43] opened 2019-07-08 15:45 UTC
Dear all. I have problems with the prerequisites of the lab. The VM that comes with the template always gives the same error (regarding NLA). I've taken several steps to solve this problem but don't manage to establish a connection. 

_"your windows DC cannot be contacted to perform NLA."_

**Comment by DawnmarieDesJardins** [comment] 2019-07-08 16:29
@mwasham 
Hi Michael, 
Please review and advise.
Dawnmarie

**Comment by paulopsgility** [comment] 2019-07-29 23:06
@AnneleenArtois  There is no domain controller and no domain joined VM that is deployed as part of this MCW. Where are you seeing this? When you try to connect to SQLCohoDW?

**Comment by AnneleenArtois** [comment] 2019-07-30 12:57
Exactly. 

I redeployed it a couple of times a few weeks ago and I got this NLA error every time. I tried again today and got twice  a "Your credentials didn't work"  error. I just don't manage to connect.

**Comment by paulopsgility** [comment] 2019-07-30 13:46
@AnneleenArtois What region are you using?

**Comment by AnneleenArtois** [comment] 2019-07-30 13:48
@paulopsgility N Europe.

**Comment by paulopsgility** [comment] 2019-07-30 15:20
@AnneleenArtois I was not able to reproduce this even in N Europe. When you connect, make sure that RDP is not picking up your corporate domain. If it does that then you will not be able to connect. 

An easy way to test would be to use a personal machine to make the connection. That gets you off of your corporate network so the domain should not be an issue. Of course, you do not want to have VPN enabled when you do this.

**Comment by AnneleenArtois** [comment] 2019-07-31 12:39
@paulopsgility Solved !

**Comment by DawnmarieDesJardins** [comment] 2019-07-31 22:25
@AnneleenArtois @paulopsgility 
Spectacular, thank you!  Closing issue as resolved.

**Closed by DawnmarieDesJardins** 2019-07-31 22:25 UTC
